- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "/lidar_scan"
  gz_topic_name: "/lidar_scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "camera/camera_info"
  gz_topic_name: "camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "tf"
  gz_topic_name: "tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "diff_cont/cmd_vel_unstamped"
  gz_topic_name: "cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "joint_states"
  gz_topic_name: "joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "ignition.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/gz/sensor/imu_data"
  gz_topic_name: "/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/gz/sensor/mag"
  gz_topic_name: "/magnetometer"
  ros_type_name: "sensor_msgs/msg/MagneticField"
  gz_type_name: "ignition.msgs.Magnetometer"
  direction: GZ_TO_ROS

- ros_topic_name: "/gz/sensor/gps_fix"
  gz_topic_name: "/nav_msgs"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "ignition.msgs.NavSat"
  direction: GZ_TO_ROS

- ros_topic_name: "/gz/sensor/ultrasonic_read"
  gz_topic_name: "/ultrasonic/scan"
  ros_type_name: "sensor_msgs/msg/Range"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/gz/sensor_sim/ir_left"
  gz_topic_name: "/sensor/gazebo_ir_left_sensor"
  ros_type_name: "sensor_msgs/msg/Range"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/gz/sensor_sim/ir_right"
  gz_topic_name: "/sensor/gazebo_ir_right_sensor"
  ros_type_name: "sensor_msgs/msg/Range"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: GZ_TO_ROS

# Pose robot depuis Gazebo (pour odométrie)
- ros_topic_name: "/model/hexapod_pkg/pose"
  gz_topic_name: "/world/slam_test_world/pose/info"
  ros_type_name: "geometry_msgs/msg/PoseArray"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: GZ_TO_ROS
